trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)/function'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: 'Apresentacao/TorneioLeft4Dead2FunctionApp/TorneioLeft4Dead2FunctionApp.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build Project'
  inputs:
    command: 'build'
    projects: 'Apresentacao/TorneioLeft4Dead2FunctionApp/TorneioLeft4Dead2FunctionApp.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish Project'
  inputs:
    command: 'publish'
    projects: 'Apresentacao/TorneioLeft4Dead2FunctionApp/TorneioLeft4Dead2FunctionApp.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(outputDir)'
    publishWebProjects: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(outputDir)'
    ArtifactName: 'function'
